INSERT INTO CATEGORY(NAME)
    VALUES ('CAKE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('Cupcake', 1000, 400, 0, NULL, 'CAKE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('Chocolate Cake', 5000, 2000, 0, NULL, 'CAKE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('Pound Cake', 3000, 1500, 0, NULL, 'CAKE');

INSERT INTO PURCHASE(NAME, QUANTITY)
    VALUES ('Pound Cake', 3);


INSERT INTO CATEGORY(NAME)
    VALUES ('COFFEE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('Dutch Coffee', 3000, 500, 0, NULL, 'COFFEE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('Cafe Mocha', 4000, 1500, 0, NULL, 'COFFEE');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('Black Coffee', 2000, 500, 0, NULL, 'COFFEE');

INSERT INTO PURCHASE(NAME, QUANTITY)
    VALUES ('Black Coffee', 5);

INSERT INTO PURCHASE(NAME, QUANTITY)
    VALUES ('Black Coffee', 2);


INSERT INTO CATEGORY(NAME)
    VALUES ('TEST');

INSERT INTO MENU(NAME, PRICE, COST, TAX_MODE, BARCODE, CATEGORY_NAME)
    VALUES ('test', 2000, 500, 0, NULL, 'TEST');
