language: node_js
node_js:
    - '0.10'
    - '0.11'
before_script:
  - npm install bower grunt-cli -g
  - npm install
  - bower install
script:
  grunt test
notifications:
    slack: suji:3sWST48WZ1iwOscMAWuGbcR4
addons:
  mariadb: '10.0'
