CREATE TABLE USER (
    ID VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    ADMIN_PASSWORD VARCHAR(20) NOT NULL,
    JOIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);

CREATE TABLE SHOP (
    ID INT NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    REPRESENT VARCHAR(20) DEFAULT NULL,
    ADDRESS VARCHAR(150) DEFAULT NULL,
    TELEPHONE VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CATEGORY (
    NAME VARCHAR(100) NOT NULL,
    SHOPPK INT NOT NULL,
    PRIMARY KEY(NAME),
    FOREIGN KEY(SHOPPK) REFERENCES SHOP(ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE PRODUCT (
    NAME VARCHAR(100) NOT NULL,
    PRICE INT NOT NULL,
    COST INT NOT NULL,
    TAX TINYINT(1) NOT NULL,
    BARCODE VARCHAR(150) DEFAULT NULL,
    CATEGORYPK VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY(NAME)
    );

