INSERT INTO USER(ID, PASSWORD, ADMIN_PASSWORD)
    VALUES ('TAK', 'TakPassword', 'AdminPassword');

INSERT INTO SHOP(ID, NAME, REPRESENT, ADDRESS, TELEPHONE)
    VALUES (1, 'SHOP1', 'MR.KIM', 'SEOUL', '010-1111-2222');

INSERT INTO CATEGORY(NAME, SHOPPK)
    VALUES ('FOOD', 1);

INSERT INTO PRODUCT(NAME, PRICE, COST, TAX, BARCODE, CATEGORYPK)
    VALUES ('BREAD', 500, 400, 0, NULL, 'FOOD');

INSERT INTO PRODUCT(NAME, PRICE, COST, TAX, BARCODE, CATEGORYPK)
    VALUES ('CHICKEN', 1000, 500, 0, NULL, 'FOOD');
