var DUPLICATE = 100;
var INSERT_USER = 101;
var INSERT_CATEGORY = 102;
var NO_SHOP = 103;

exports.DUPLICATE = DUPLICATE;
exports.INSERT_USER = INSERT_USER;
exports.INSERT_CATEGORY = INSERT_CATEGORY;
exports.NO_SHOP = NO_SHOP;


//v1.1
var INSERT_MENU = 104;
var NO_CATEGORY_NAME = 105;
exports.INSERT_MENU = INSERT_MENU;
exports.NO_CATEGORY_NAME = NO_CATEGORY_NAME;
