var DUPLICATE = 100;
var INSERT_USER = 101;
var INSERT_CATEGORY = 102;
var NO_SHOP = 103;

exports.DUPLICATE = DUPLICATE;
exports.INSERT_USER = INSERT_USER;
exports.INSERT_CATEGORY = INSERT_CATEGORY;
exports.NO_SHOP = NO_SHOP;


//v1.1
var INSERT_MENU = 104;
var NO_NAME_IN_CATEGORY = 105;
var DELETE_MENU = 106;
var NO_NAME_IN_MENU = 107;
exports.INSERT_MENU = INSERT_MENU;
exports.NO_NAME_IN_CATEGORY = NO_NAME_IN_CATEGORY;
exports.DELETE_MENU = DELETE_MENU;
exports.NO_NAME_IN_MENU = NO_NAME_IN_MENU;
