var DUPLICATE = 100;
var INSERT_USER = 101;
var INSERT_CATEGORY = 102;
var NO_SHOP = 103;

exports.DUPLICATE = DUPLICATE;
exports.INSERT_USER = INSERT_USER;
exports.INSERT_CATEGORY = INSERT_CATEGORY;
exports.NO_SHOP = NO_SHOP;
