CREATE TABLE CATEGORY (
    NAME VARCHAR(100) NOT NULL
);

ALTER TABLE CATEGORY
    ADD PRIMARY KEY (
            NAME
);

CREATE TABLE MENU (
    NAME          VARCHAR(100) NOT NULL COMMENT '메뉴명',
    PRICE         INT          NOT NULL COMMENT '가격',
    COST          INT          NOT NULL COMMENT '원가',
    TAX_MODE      TINYINT(1)   NOT NULL COMMENT '세금/면세 상품 여부',
    BARCODE       VARCHAR(150) NULL     COMMENT '바코드',
    CATEGORY_NAME VARCHAR(100) NULL     COMMENT 'CATEGORY PK'
);
ALTER TABLE MENU
    ADD
        PRIMARY KEY (
            NAME
);

CREATE TABLE HISTORY (
    TIME     TIMESTAMP  NOT NULL COMMENT '계산시간',
    TABLE_NO TINYINT    NOT NULL COMMENT '테이블번호',
    MODE     TINYINT(1) NOT NULL COMMENT '현금, 카드 결제 여부'
);
ALTER TABLE HISTORY
    ADD
        PRIMARY KEY (
            TIME
        );

CREATE TABLE HISTORY_DETAIL (
    HISTORY_TIME TIMESTAMP    NOT NULL COMMENT 'HISTORY PK',
    MENU_NAME    VARCHAR(100) NOT NULL COMMENT 'MENU PK',
    QUANTITY     TINYINT      NOT NULL COMMENT '개수(기본값 1)'
);

CREATE TABLE INFO (
    NAME            VARCHAR(100) NOT NULL COMMENT '매장명',
    OWNER           VARCHAR(100) NULL     COMMENT '대표자명',
    ADMIN_PASSWORD  VARCHAR(150) NOT NULL COMMENT '관리자비밀번호',
    ADDRESS         VARCHAR(150) NULL     COMMENT '매장주소',
    PHONE           VARCHAR(150) NULL     COMMENT '매장전화번호',
    BUSINESS_NUMBER VARCHAR(150) NULL     COMMENT '사업자등록번호',
    GENERATE_DATE   TIMESTAMP    NOT NULL COMMENT '등록일자'
);
ALTER TABLE INFO
    ADD
        PRIMARY KEY (
            NAME
        );

ALTER TABLE MENU
    ADD
        FOREIGN KEY (
            CATEGORY_NAME
        )
        REFERENCES CATEGORY (
            NAME
        );

ALTER TABLE HISTORY_DETAIL
    ADD
        FOREIGN KEY (
            HISTORY_TIME
        )
        REFERENCES HISTORY (
            TIME
        );

ALTER TABLE HISTORY_DETAIL
    ADD
        FOREIGN KEY (
            MENU_NAME
        )
        REFERENCES MENU (
            NAME
        );

INSERT INTO CATEGORY(NAME)
    VALUES ('FOOD');
